/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.m11_fichatrab4;

import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import javax.swing.JOptionPane;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

/**
 *
 * @author a22145
 */
public class M11_fichaTrab4 extends javax.swing.JFrame {

    /**
     * Creates new form M11_fichaTrab4_
     */
    public M11_fichaTrab4() {
        initComponents();
        Contem.setSelected(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        gravar = new javax.swing.JButton();
        carac = new javax.swing.JComboBox<>();
        Comeca = new javax.swing.JCheckBox();
        Contem = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Procurar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gravar.setText("gravar resultados");
        gravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gravarMouseClicked(evt);
            }
        });

        carac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));

        Comeca.setText("Começa com...");
        Comeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComecaActionPerformed(evt);
            }
        });

        Contem.setText("contém...");
        Contem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContemActionPerformed(evt);
            }
        });

        jLabel1.setText("Minimo de carateres:");

        jLabel2.setText("Opçoes:");

        jLabel3.setText("Palavra a procurar:");

        Procurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcurarActionPerformed(evt);
            }
        });
        Procurar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ProcurarKeyReleased(evt);
            }
        });

        TextArea.setEditable(false);
        TextArea.setBackground(new java.awt.Color(0, 0, 0));
        TextArea.setColumns(20);
        TextArea.setForeground(new java.awt.Color(255, 255, 255));
        TextArea.setRows(5);
        TextArea.setCaretColor(new java.awt.Color(255, 255, 255));
        TextArea.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(TextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(gravar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Contem)
                                    .addComponent(jLabel2)
                                    .addComponent(Comeca)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(carac, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Procurar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Procurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(carac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Comeca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Contem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(gravar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gravarMouseClicked
     String termo = null;
     int carac = 0;
     String Procurar = "";
     String numeroSugestoes="";
            //List<String> sugestoes = null, ) int = 0 numeroSugestoes


        try (BufferedWriter writer = new BufferedWriter(new FileWriter("resultados.dic", true))) {
            writer.write("Termo: " + termo + "\n");
            writer.write("Mínimo de Caracteres: " + carac + "\n");
            writer.write("Opção de Procura: " + Procurar + "\n");
            
            writer.write("Sugestões:\n");
           // for (String sugestao : sugestoes) {
           //     writer.write("- " + sugestao + "\n");
           // }
            

            writer.write("Número Total de Sugestões: " + numeroSugestoes + "\n\n");
        } catch (IOException ex) {
            System.out.println("Erro ao gravar resultados: " + ex.getMessage());
        }
    
    }//GEN-LAST:event_gravarMouseClicked

    private void ProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcurarActionPerformed
       
    }//GEN-LAST:event_ProcurarActionPerformed

    private void ComecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComecaActionPerformed
         //Contem.setSelected(true);
         
         Contem.setSelected(true);
          
         //Contem.setAction(true);
         
    }//GEN-LAST:event_ComecaActionPerformed

    private void ContemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContemActionPerformed
        // Contem.setSelected(true);
        Comeca.setSelected(true);
        
       
         //Comeca.setAction(true);
         
    }//GEN-LAST:event_ContemActionPerformed

    private void ProcurarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProcurarKeyReleased
        // TODO add your handling code here:
        ler();
    }//GEN-LAST:event_ProcurarKeyReleased
    public void ler(){
    String p;    // palavra lida do ficheiro.
    String textp=Procurar.getText();
    boolean inicio;
    boolean tem;
    String Textof="";
    String Texto="";
    int conttotal=0;
    int contint=0;
        try {            
            RandomAccessFile r = new RandomAccessFile("palavras.bin", "r");
               
            while(r.getFilePointer()<r.length()){
            
                p = r.readUTF();
               inicio= p.startsWith(textp);
               tem=p.contains(textp);
                conttotal++;
            
               if(Comeca.isSelected()&&inicio ){
                  Texto=Texto+p+"\n"; 
                  contint++;
               }else if(Contem.isSelected()&&tem){
                   Texto=Texto+p+"\n";  
                   contint++;
               }
                TextArea.append(Texto+"\n");
                
            }
            r.close();
        } catch (FileNotFoundException ex) {
            System.out.println("ERRO: onde está o ficheiro?");
        } catch (IOException ex) {
            System.out.println("OOOPS "+ex);
        }
} 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(M11_fichaTrab4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(M11_fichaTrab4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(M11_fichaTrab4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(M11_fichaTrab4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new M11_fichaTrab4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Comeca;
    private javax.swing.JCheckBox Contem;
    private javax.swing.JTextField Procurar;
    private javax.swing.JTextArea TextArea;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> carac;
    private javax.swing.JButton gravar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
